// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthorGrid: typeof import('./src/components/ui/AuthorGrid.vue')['default']
    BaseDetailGrid: typeof import('./src/components/base-ui/BaseDetailGrid.vue')['default']
    BaseEntity: typeof import('./src/components/base-ui/BaseEntity.vue')['default']
    BaseGrid: typeof import('./src/components/base-ui/BaseGrid.vue')['default']
    BasePicker: typeof import('./src/components/base-ui/BasePicker.vue')['default']
    BaseSecurity: typeof import('./src/components/base-ui/BaseSecurity.vue')['default']
    Book: typeof import('./src/components/Book.vue')['default']
    BookGrid: typeof import('./src/components/ui/BookGrid.vue')['default']
    BookInfo: typeof import('./src/components/ui/BookInfo.vue')['default']
    BooklistView: typeof import('./src/components/BooklistView.vue')['default']
    BookPointView: typeof import('./src/components/BookPointView.vue')['default']
    BookRegister: typeof import('./src/components/ui/BookRegister.vue')['default']
    Boolean: typeof import('./src/components/primitives/Boolean.vue')['default']
    BuyNow: typeof import('./src/@core/components/BuyNow.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    Date: typeof import('./src/components/primitives/Date.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    EventViewer: typeof import('./src/components/vo/EventViewer.vue')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    LargeObject: typeof import('./src/components/primitives/LargeObject.vue')['default']
    LoginDialog: typeof import('./src/components/vo/LoginDialog.vue')['default']
    ManageAuthorRequests: typeof import('./src/components/ui/ManageAuthorRequests.vue')['default']
    MyPage: typeof import('./src/components/ui/MyPage.vue')['default']
    Number: typeof import('./src/components/primitives/Number.vue')['default']
    OpenBook: typeof import('./src/components/OpenBook.vue')['default']
    ReadBook: typeof import('./src/components/ui/ReadBook.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/components/SignUp.vue')['default']
    String: typeof import('./src/components/primitives/String.vue')['default']
    SubscribeGrid: typeof import('./src/components/ui/SubscribeGrid.vue')['default']
    SubscribeMonitorView: typeof import('./src/components/SubscribeMonitorView.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
  }
}
