name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./book/pom.xml
          mvn clean package -f ./subscribe/pom.xml
          mvn clean package -f ./user/pom.xml
          mvn clean package -f ./manage/pom.xml
          mvn clean package -f ./plan/pom.xml
          mvn clean package -f ./ai 출간 서비스/pom.xml

      - name: Docker Build and push for Book
        uses: docker/build-push-action@v4
        with:
          context: ./book
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/book:latest
            ghcr.io/${{ github.repository }}/book:${{ github.ref_name }}
            
      - name: Docker Build and push for Subscribe
        uses: docker/build-push-action@v4
        with:
          context: ./subscribe
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/subscribe:latest
            ghcr.io/${{ github.repository }}/subscribe:${{ github.ref_name }}
            
      - name: Docker Build and push for User
        uses: docker/build-push-action@v4
        with:
          context: ./user
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user:latest
            ghcr.io/${{ github.repository }}/user:${{ github.ref_name }}
            
      - name: Docker Build and push for Manage
        uses: docker/build-push-action@v4
        with:
          context: ./manage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/manage:latest
            ghcr.io/${{ github.repository }}/manage:${{ github.ref_name }}
            
      - name: Docker Build and push for Plan
        uses: docker/build-push-action@v4
        with:
          context: ./plan
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/plan:latest
            ghcr.io/${{ github.repository }}/plan:${{ github.ref_name }}
            
      - name: Docker Build and push for Ai출간서비스
        uses: docker/build-push-action@v4
        with:
          context: ./ai 출간 서비스
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ai-출간-서비스:latest
            ghcr.io/${{ github.repository }}/ai-출간-서비스:${{ github.ref_name }}
            
