# docker-compose.yml (Bitnami KRaft 모드 최종 버전)

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      # === Bitnami KRaft 모드 환경 변수 설정 ===

      # 1. KRaft 모드 활성화 및 역할 부여
      - KAFKA_CFG_PROCESS_ROLES=broker,controller # 👈 에러가 요구했던 바로 그 설정!
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      
      # 2. 리스너 설정
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      
      # 3. PLAINTEXT 리스너 사용 허용 (필수)
      - ALLOW_PLAINTEXT_LISTENER=yes
      
      # 4. 자동 토픽 생성 활성화
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true