server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: book
          uri: http://localhost:8082
          predicates:
            - Path=/undefined/**, 
        - id: subscribe
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, 
        - id: user
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, 
        - id: manage
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, 
        - id: plan
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, 
        - id: ai 출간 서비스
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: book
          uri: http://book:8080
          predicates:
            - Path=/undefined/**, 
        - id: subscribe
          uri: http://subscribe:8080
          predicates:
            - Path=/undefined/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/undefined/**, 
        - id: manage
          uri: http://manage:8080
          predicates:
            - Path=/undefined/**, 
        - id: plan
          uri: http://plan:8080
          predicates:
            - Path=/undefined/**, 
        - id: ai 출간 서비스
          uri: http://ai출간서비스:8080
          predicates:
            - Path=/undefined/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
