server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: book
          uri: http://localhost:8082
          predicates:
            - Path=/books/**, 
        - id: user
          uri: http://localhost:8083
          predicates:
            - Path=/users/**, /subscribes/**, /bookPoints/**
        - id: bookpublish
          uri: http://localhost:8084
          predicates:
            - Path=/genData/**, 
        - id: author
          uri: http://localhost:8085
          predicates:
            - Path=/authors/**,/authors-requests/**
        - id: dashboard
          uri: http://localhost:8086
          predicates:
            - Path=, /subscribeMonitors/**, /booklists/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: book
          uri: http://book:8080
          predicates:
            - Path=/books/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, /subscribes/**, 
        - id: bookpublish
          uri: http://bookpublish:8080
          predicates:
            - Path=/genData/**, 
        - id: author
          uri: http://author:8080
          predicates:
            - Path=/authors/**,/authors-requests/**
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
